services:
  client:
    container_name: prakticum-client
    image: prakticum-client
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        CLIENT_PORT: ${CLIENT_PORT}
    restart: always
    ports:
      - "${CLIENT_PORT}:3000"
    networks:
      - custom_network  # Подключение к кастомной сети
    environment:
      - CLIENT_PORT=${CLIENT_PORT}
      - SERVER_PORT=${SERVER_PORT}
      - EXTERNAL_SERVER_URL=${EXTERNAL_SERVER_URL}
      - INTERNAL_SERVER_URL=${INTERNAL_SERVER_URL}

  server:
    container_name: prakticum-server
    env_file: .env
    image: prakticum-server
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - custom_network  # Подключение к кастомной сети
    environment:
      - SERVER_PORT=${SERVER_PORT}
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    networks:
      - custom_network  # Подключение к кастомной сети

networks:
  custom_network:
    driver: bridge  # Использование драйвера bridge
