ARG NODE_VERSION=18
ARG SERVER_PORT=3001

FROM node:$NODE_VERSION-alpine as base

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .
RUN yarn lerna bootstrap && yarn build --scope=server

FROM node:$NODE_VERSION-alpine as production
WORKDIR /app

COPY --from=base /app/packages/server/dist/ /app/
COPY --from=base /app/packages/server/package.json /app/package.json

RUN yarn install --production

EXPOSE $SERVER_PORT
CMD [ "node", "/app/index.js" ]
