export const EFFECT_ADDLIFE = 'addlife'
export const EFFECT_DAMAGELIFE = 'damagelife'
export const EFFECT_RAPIDBALL = 'rapidball'
export const EFFECT_WIDEPLATFORM = 'wideplatform'
export const EFFECT_GEM = 'gem'
